import { NotifierConfig } from "../src/config/schema.js";

export const testEnv = {
  mqttUrl: "mqtt://example.invalid:1883",
  mqttUsername: "test-user",
  mqttPassword: "test-password",
  mqttTopics: ["frigate/reviews"],
  homeAssistantOpenClawTopic: "notifier-test/openclaw/send",
  homeAssistantOpenClawControlCommandTopic: "notifier-test/openclaw/set",
  homeAssistantOpenClawControlStateTopic: "notifier-test/openclaw/state",
  alertControlCommandTopic: "notifier-test/alerts/set",
  alertControlStateTopic: "notifier-test/alerts/state",
  alertControlCameraTopicPrefix: "notifier-test/alerts",
  homeAssistantDiscoveryPrefix: "homeassistant-test",
  homeAssistantDeviceId: "notifier_test",
  homeAssistantDeviceName: "Notifier Test",
  frigateBaseUrl: "http://frigate.example.invalid/api",
  frigateLocalClipsDir: "/tmp/frigate-local-clips-test",
  openclawTarget: "+56000000000",
  openclawGroupId: "test-group@g.us",
  mediaTmpDir: "/tmp/frigate-openclaw-test",
  ffmpegBin: "ffmpeg",
  messageTimeZone: "America/Santiago",
  cameraName: "test-camera",
  secondCameraName: "test-camera-2",
  eventZone: "test-zone",
  mediaPath: "/tmp/e1.jpg"
} as const;

export function makeConfig(overrides: Partial<NotifierConfig> = {}): NotifierConfig {
  return {
    mqttUrl: testEnv.mqttUrl,
    mqttTopics: [...testEnv.mqttTopics],
    homeAssistantOpenClawTopic: testEnv.homeAssistantOpenClawTopic,
    homeAssistantOpenClawControlCommandTopic: testEnv.homeAssistantOpenClawControlCommandTopic,
    homeAssistantOpenClawControlStateTopic: testEnv.homeAssistantOpenClawControlStateTopic,
    homeAssistantOpenClawDefaultEnabled: true,
    alertControlCommandTopic: testEnv.alertControlCommandTopic,
    alertControlStateTopic: testEnv.alertControlStateTopic,
    alertControlDefaultEnabled: true,
    alertControlCameraTopicPrefix: testEnv.alertControlCameraTopicPrefix,
    homeAssistantDiscoveryEnabled: true,
    homeAssistantDiscoveryPrefix: testEnv.homeAssistantDiscoveryPrefix,
    homeAssistantDeviceId: testEnv.homeAssistantDeviceId,
    homeAssistantDeviceName: testEnv.homeAssistantDeviceName,
    frigateBaseUrl: testEnv.frigateBaseUrl,
    frigateUseLocalMedia: false,
    frigateLocalClipsDir: testEnv.frigateLocalClipsDir,
    openclawBin: "openclaw",
    openclawChannel: "whatsapp",
    openclawTarget: testEnv.openclawTarget,
    openclawGroupId: testEnv.openclawGroupId,
    openclawTargets: [testEnv.openclawTarget, testEnv.openclawGroupId],
    notifyOnReviewNew: true,
    notifyOnReviewUpdate: false,
    notifyOnReviewEnd: false,
    sendSnapshot: true,
    sendClip: false,
    minSeverities: ["alert"],
    allowedCameras: [],
    allowedObjects: [],
    blockedZones: [],
    cooldownSeconds: 90,
    mediaTmpDir: testEnv.mediaTmpDir,
    mediaRetentionSeconds: 3600,
    ffmpegBin: testEnv.ffmpegBin,
    videoProcessTimeoutMs: 120_000,
    clipRetryAttempts: 3,
    clipRetryDelayMs: 3000,
    messageTimeZone: testEnv.messageTimeZone,
    logLevel: "info",
    openclawTimeoutMs: 30_000,
    frigateFetchTimeoutMs: 15_000,
    ...overrides
  };
}
